### ISSUE TITLE
Polar fails to sync to Anki when note type "Basic" is not present

### ISSUE THREAD

**Issue by aleksandar-j** [burtonator/polar-bookshelf#779] opened 2019-03-25 19:35 UTC
**Describe the bug**
When I try to sync with Anki I get errors. I look through logs and see card type name says "Basic". For greater organization, I don't use "Basic" but "-- Basic --" as card type name. Polar fails to sync. As soon as I create "Basic" card type, Polar syncs. I'd rather not have "Basic" card type in Anki, so maybe some easy to set option for card name would be a better solution?

**To Reproduce**
1. Open Polar
2. Sync flashcards
3. See errors if your Anki note types list contains no "Basic" card type

**Expected behavior**
Not sure what to expect here, I wouldn't like Polar to automatically create "Basic" card type. So, maybe some user-set option should be available? At the very least, there should be a user readable error so people don't have to waste time searching for a reason on why it doesn't work.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Firefox
 - Version 18.10

**Comment by burtonator** [comment] 2019-03-27 20:58
Yeah.. I'm not sure what to do about this either.  It's a tough call.

**Comment by Apetited** [comment] 2019-08-10 17:04
Definitely agree that Polar should issue an error when this happens. Otherwise it's really hard for the user to know what the problem is, while being fairly easy to fix once they do know.

**Comment by burtonator** [comment] 2019-08-10 17:28
This can be resolved by calling modelNames and then returning an error if our required deck names aren't present.

https://foosoft.net/projects/anki-connect/index.html#models

modelNames

Gets the complete list of model names for the current user.

Sample request:

{
    "action": "modelNames",
    "version": 6
}
Sample result:

{
    "result": ["Basic", "Basic (and reversed card)"],
    "error": null
}

**Comment by burtonator** [comment] 2019-08-10 18:01
Fixed in the next release.

**Closed by burtonator** 2019-08-10 18:01 UTC
Labels: usability
