### ISSUE TITLE
Error creating pagemark

### ISSUE THREAD

**Issue by garrettqmartin8** [burtonator/polar-bookshelf#620] opened 2019-02-11 14:16 UTC
**Describe the bug**
Creating a pagemark does not work and causes the following error message:

> [PagemarkCoverageEventListener.js] Error: Assertion failed for value 800: Progress value invalid. Must be within interval [0-100]

**To Reproduce**
I can only reproduce this on my PDF copy of "The Go Programming Language", but here's a screen recording:

![demo](https://user-images.githubusercontent.com/3522323/52568676-0c59b380-2dd5-11e9-9db7-ac4755378e3d.gif)

**Expected behavior**
It should be adding a pagemark.

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.2
 - Polar Bookshelf Version 10.12.0

**Comment by burtonator** [comment] 2019-02-11 20:15
Could you share a copy of the pdf and what page it happens on? looks like page 34.. I could ship a build with mroe debug info here though

**Comment by garrettqmartin8** [comment] 2019-02-11 22:40
Unfortunately, it's happening on every page. Even after quitting and reopening.

Is there a way I can privately share the PDF with you? I'd like to be be mindful of not distributing the authors' work publicly.

**Comment by burtonator** [comment] 2019-02-11 22:42
oh sure.. send me a link to burton ... _at  getpolarized  ... dot io.

Obfuscated that so bots don't spam me. 

I'll delete it when done.  it's probably something weird with irregular page width or something but definitely should not happen.

**Comment by burtonator** [comment] 2019-02-11 22:43
does it only happen with 'create pagemark at point' or what about  'create pagemark' ?

**Comment by garrettqmartin8** [comment] 2019-02-12 16:21
Sent! I can create a pagemark box just fine. It's only failing on "create pagemark at point". One thing that might provide helpful context: each subsequent time I try to create a pagemark at point, the "Assertion value failed" number increases by 100. In the original error message I posted, the value was 800. Now it's 1400.

**Comment by garrettqmartin8** [comment] 2019-03-04 17:26
This same issue seems to be happening in another PDF book. I'll email it to you.

**Comment by garrettqmartin8** [comment] 2019-03-05 18:45
Also, if you'd like to point me in the right direction, I can try to contribute a fix for this myself! I know you're working on tons of different features.

**Comment by burtonator** [comment] 2019-03-05 18:50
Can you try in 1.13.9 ? I made some changes here.  you can just go to Help  | Update to force it to update for you.

**Comment by garrettqmartin8** [comment] 2019-03-05 18:55
Still getting the same error. The progress value that seems to be invalid is still increasing by 100 each time I try to create a pagemark.

**Comment by burtonator** [comment] 2019-03-05 19:08
ok.. I've definitely been able to reproduce it but only once...

**Comment by burtonator** [comment] 2019-03-05 19:09
could you try removing all the pagemarks and re-creating them?  I wonder if the issue is legacy pagemarks...

**Comment by garrettqmartin8** [comment] 2019-03-05 19:57
Ah, interesting. That worked for the second document that I sent you. However, the first one (the Golang book) is still throwing the same error. I deleted the pagemark, but the pagemark progress bar still indicates some progress, so there might be some stale pagemark data hanging around.

**Comment by burtonator** [comment] 2019-03-05 20:14
WEIRD.. try exiting and coming back in?  that's definitely a bug if there are invisible pagemarks!!!

**Comment by burtonator** [comment] 2019-03-05 20:15
I think I"m going to add an option to copy the docMeta to the clipboard so people can include them in tickets.. this would make it easer to debug

**Comment by garrettqmartin8** [comment] 2019-03-05 20:30
Where can I manually find the docMeta? I'll paste it here so you can get a clearer picture.

**Comment by garrettqmartin8** [comment] 2019-03-05 20:34
I think I found it in ~/.polar: [state.zip](https://github.com/burtonator/polar-bookshelf/files/2932738/state.zip)

**Comment by sopoforic** [comment] 2019-05-01 18:10
This bug is now fixed.

**Closed** 2019-05-02 14:38 UTC
