### ISSUE TITLE
Text selection disapears but highlight bar remains

### ISSUE THREAD

**Issue by or-dodson** [burtonator/polar-bookshelf#1338] opened 2020-01-22 00:18 UTC
**Describe the bug**
Clicking on anywhere besides a button on the highlight bar removes text highlight and makes it not able to be highlighted, but highlight menu remains

**To Reproduce**
1. Highlight text
2. Click anywhere besides a color on highlight menu

**Expected behavior**
Text highlight and highlight menu should remain

**Screenshots**
![Capture](https://user-images.githubusercontent.com/48970011/72854543-ec33a500-3c71-11ea-8593-fe8e474a68e4.JPG)

![Capture2](https://user-images.githubusercontent.com/48970011/72854544-ee95ff00-3c71-11ea-8078-803c8887dd04.JPG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Polar 1.90

**Comment by thiswillbeyourgithub** [comment] 2020-01-22 07:06
Duplicate of #1248

**Comment by or-dodson** [comment] 2020-01-22 17:25
accidentality closed -- reopening

**Comment by burtonator** [comment] 2020-07-17 01:43
should be n/a on 2.0

**Closed by burtonator** 2020-07-17 01:43 UTC
