### ISSUE TITLE
Snap not working

### ISSUE THREAD

**Issue by javenschuetz** [burtonator/polar-bookshelf#257] opened 2018-10-13 02:07 UTC
The .deb version works fine, but the snap version seems to have an issue:

```sudo snap install --channel=stable polar-bookshelf
[sudo] password for <username>: 
polar-bookshelf 1.0.1 from Kevin Burton (inputneuron) installed
<username> ~ 
$ polar-bookshelf 
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Failed to generate minidump.Segmentation fault (core dumped)```

Desktop running Ubuntu 18.04 LTS using default Gnome Desktop Environment

(neat program btw, thanks for making it)

**Comment by burtonator** [comment] 2018-10-13 02:10
This is bizarre as I'm on the same OS and the snaps work fine.. and the fact that it yields a segfault doesn't give me much to track down.

**Comment by burtonator** [comment] 2018-10-13 02:15
anything unusual about your config?

**Comment by mquandalle** [comment] 2018-10-13 19:56
I'm having the same issue, also on Ubuntu 18.04.1 LTS.

**Comment by xezpeleta** [comment] 2018-10-16 14:39
Same here. I've tried installing libcanberra-gtk-module, libcanberra-gtk0...

Still same error.

**Comment by burtonator** [comment] 2018-10-16 15:18
I might have to install Ubuntu in a vm and see what happens. Very strange.

**Comment by xezpeleta** [comment] 2018-10-16 15:36
@burtonator This may can help you: https://github.com/johannesjo/super-productivity/issues/27

**Comment by burtonator** [comment] 2018-10-16 17:16
I'm stumped on this one guys.  It seems like installing the packages doesn't have am impact on this one being fixed.  

@xezpeleta tried installing the packages and it still failed.

**Comment by burtonator** [comment] 2018-10-16 17:20
https://github.com/electron/electron/issues/13767
https://github.com/electron-userland/electron-builder/issues/2981

**Comment by burtonator** [comment] 2018-10-16 17:20
Might be related to sentry...

**Comment by burtonator** [comment] 2018-10-16 19:02
I'm going to re-release tonight or tomorrow morning with an updated sentry package to see if this fixes the problem.

**Comment by cdancette** [comment] 2018-10-17 21:21
Same error, using ubuntu 18 and plasma desktop

**Comment by burtonator** [comment] 2018-10-17 22:28
Could you guys try again to refresh with 1.0.3 ?

I'm only about 50/50 on whether this will fix it... I have a hunch what the solution is though. Once we get them working it will be easier to maintain them in the future.

**Comment by xezpeleta** [comment] 2018-10-18 06:08
Sorry, it didn't work :(

```
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Failed to generate minidump.Segmentation fault (core dumped)
```

**Comment by berkes** [comment] 2018-10-18 12:19
Same issue here on 1.0.3. I'm not familiar with the exact outline of snap (other that *it is weird and complex*) so I could not create a strace. If someone can explain how to do this with snap, I'd love to help create some logs.

`strace snap run polar-bookshelf`gives a `need to run as root or suid` and `sudo strace snap run polar-bookshelf` fails on permissions since it tries to run polar-bookshelf snap in roots snap environment.

**Comment by burtonator** [comment] 2018-10-18 17:49
hm.. ok.. until I can fix this the .deb packages will have to work. Or someone can try to get AppImage to work.

Another idea could be to comment out the use of sentry and see if that fixes things.

**Comment by javenschuetz** [comment] 2018-10-19 02:15
In case it helps, signal-desktop is occasionally failing to open for me lately as well. Similar error related to canberra-gtk-module. There are a few ddg results when you look for 'ubuntu snaps canberra-gtk-module problem'

I'm not certain how snaps work, but did Canonical change what version of the module its using by default in the snaps? (Sorry for not being able to offer something more concrete, not sure how the guts of snaps work)

```$ signal-desktop 
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Set Windows Application User Model ID (AUMID) { appUserModelId: 'org.whispersystems.signal-desktop' }
NODE_ENV production
NODE_CONFIG_DIR /snap/signal-desktop/93/resources/app.asar/config
NODE_CONFIG {}
ALLOW_CONFIG_MUTATIONS undefined
HOSTNAME undefined
NODE_APP_INSTANCE undefined
SUPPRESS_NO_CONFIG_WARNING undefined
userData: /home/jammygit/snap/signal-desktop/93/.config/Signal
config/get: Successfully read user config file
config/get: Successfully read ephemeral config file
making app single instance
{"name":"log","hostname":"jammygit-All-Series","pid":12075,"level":30,"msg":"app ready","time":"2018-10-19T02:08:50.979Z","v":0}
{"name":"log","hostname":"jammygit-All-Series","pid":12075,"level":30,"msg":"updateSchema: Current schema version: 3; Most recent schema version: 3; SQLite version: 3.20.1; SQLCipher version: 3.4.2;","time":"2018-10-19T02:08:51.007Z","v":0}
{"name":"log","hostname":"jammygit-All-Series","pid":12075,"level":30,"msg":"Ensure attachments directory exists","time":"2018-10-19T02:08:51.008Z","v":0}
{"name":"log","hostname":"jammygit-All-Series","pid":12075,"level":30,"msg":"Initializing BrowserWindow config: {\"show\":true,\"width\":923,\"height\":633,\"minWidth\":640,\"minHeight\":360,\"autoHideMenuBar\":false,\"webPreferences\":{\"nodeIntegration\":false,\"nodeIntegrationInWorker\":false,\"preload\":\"/snap/signal-desktop/93/resources/app.asar/preload.js\",\"nativeWindowOpen\":true},\"icon\":\"/snap/signal-desktop/93/resources/app.asar/images/icon_256.png\",\"maximized\":false,\"x\":863,\"y\":392}","time":"2018-10-19T02:08:51.010Z","v":0}
Trace/breakpoint trap (core dumped)```

**Comment by javenschuetz** [comment] 2018-10-19 02:36
Found some people attributing similar crashes to this: https://github.com/electron/electron/issues/13767

**Comment by burtonator** [comment] 2018-10-20 02:45
If anyone wants to volunteer I can give you some instructions to test.

I think it's related to Sentry.. just need to disable it and try the snap locally. 

Should be a matter of commenting out sentry, then building a new snap , installing it, and testing it.

**Comment by burtonator** [comment] 2018-10-20 17:59
yeah.. I've confirmed that the problem is sentry...

**Comment by burtonator** [comment] 2018-10-20 18:07
Bad news is I can't get snaps to run until this bug is fixed with either Electron or Sentry... 

Good news is that AppImages work just fine so I'm going to push those for a while until we can fix our snaps.

The tar.gz works fine too.

**Comment by popey** [comment] 2018-10-25 17:40
The segfault shouldn't happen though, so I filed a [thread](https://forum.snapcraft.io/t/apparmor-error-with-org-freedesktop-login1-manager/8164) on the snapcraft forum. 

What exactly is needed to completely remove sentry from a build to test it?

**Comment by burtonator** [comment] 2018-10-25 17:50
Right now the best way to debug this is to just comment out sentry to disable it while testing.

Polar "works" at this point but it can't find documents in the home directory.

So we need to fix that part first.  

In theory you could just comment out this line:

https://github.com/burtonator/polar-bookshelf/blob/cac8a4b68f292492f4a6df1f0c3c4ac07c68c0d8/web/js/logger/Logging.ts#L59

And build it again. Though you might also need to comment out the sentry import but I don't think its is required.

At that point the snap builds and works but when polar starts it doesn't see any directories in your home dir.  Not sure why...  I think the 'home' plugin isn't being used for some reason.

**Comment by burtonator** [comment] 2018-10-25 17:52
We're also running the lastest electron-builder (just checked) so upgrading that won't help.  

Once we can get it seeing files in the home dir then all we would need to do is maybe have some sort of configuration to disable sentry when running in the snap version. 

It might be nice to have a "build configuration" file to disable features for certain builds on startup.

I'd like to keep sentry running for the other Linux builds because otherwise I'm blind to issues on Linux.

**Comment by burtonator** [comment] 2018-10-25 17:52
... if there were an environment variable or something we could check to see if we're running within snap that could also be used.

**Comment by popey** [comment] 2018-10-25 18:16
If the `$SNAP` environment variable exists, you're likely inside a snap. 

Among many others:-

(the x3 in these is because I manually installed a local build, typically that would be a store revision number).

`snap run --shell polar-bookshelf` lets me enter the snap environment without running the application, so I can look at the environment.

```
$ snap run --shell polar-bookshelf
alan@hal:$ env | grep SNAP
SNAP_INSTANCE_USER_COMMON=/home/alan/snap/polar-bookshelf/common
SNAP_USER_COMMON=/home/alan/snap/polar-bookshelf/common
SNAP_CONTEXT=nwrsvK0nB15DRMvHY5jLQRvR1LpjHq1WPF23XHCpQGP8
SNAP_INSTANCE_DATA=/var/snap/polar-bookshelf/x3
SNAP_REEXEC=
SNAP_INSTANCE_COMMON=/var/snap/polar-bookshelf/common
SNAP_LIBRARY_PATH=/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl32:/var/lib/snapd/void
SNAP_COMMON=/var/snap/polar-bookshelf/common
SNAP_INSTANCE_NAME=polar-bookshelf
SNAP_USER_DATA=/home/alan/snap/polar-bookshelf/x3
SNAP_DATA=/var/snap/polar-bookshelf/x3
SNAP_REVISION=x3
SNAP_NAME=polar-bookshelf
SNAP_COOKIE=nwrsvK0nB15DRMvHY5jLQRvR1LpjHq1WPF23XHCpQGP8
SNAP_ARCH=amd64
SNAP_VERSION=1.0.4
SNAP_INSTANCE=/snap/polar-bookshelf/x3
SNAP=/snap/polar-bookshelf/x3
SNAP_INSTANCE_USER_DATA=/home/alan/snap/polar-bookshelf/x3
```

**Comment by popey** [comment] 2018-10-25 18:19
Also worth noting you can access the home directory from the working polar-bookshelf snap. I just loaded a PDF from my home/Downloads folder in it. The theme looks a bit wonky, which we're aware of. But you can access home.

![screenshot from 2018-10-25 19-17-46](https://user-images.githubusercontent.com/1841272/47521397-cc54dc00-d88a-11e8-9332-33f3504b64bb.png)

**Comment by burtonator** [comment] 2018-10-25 18:21
I will add a fix to look for $SNAP and then not run sentry.. 

The problem is that when I run snap run polar-bookshelf on my machine it immediately starts BUT I don't see any of the documents that I've been editing.

I think the $SNAP thing might be a big step int the right direction though.

**Comment by popey** [comment] 2018-10-25 18:46
> The problem is that when I run snap run polar-bookshelf on my machine it immediately starts BUT I don't see any of the documents that I've been editing.

Ah, you won't. The `home` interface only allows access to non-hidden files in the home directory. This is to prevent applications getting access to sensitive data in dot folders such as .gnupg or .ssh. 

When run, the snap has it's own confined view of the world. It will see home as ~/snap/polar-bookshelf/current  by default. So someone installing the snap, having never used the deb or other package will work just fine, with their data in the above location (referred to by $SNAP_USER_DATA). If you've used some other package, then you may want to migrate your app data into the snap home directory.

**Comment by burtonator** [comment] 2018-10-25 19:36
Shoot... so even if I used ~/.config/PolarData that wouldn't work to because it can't see .config

Is there going to be any way to map a directory into the snap?  

Kind of like docker volumes... must be some way.

**Comment by popey** [comment] 2018-10-25 21:38
If you use ~/.config/PolarData, the snap will see that as (for me, for example) `/home/alan/snap/polar-bookshelf/current/.config/PolarData` (`$SNAP_USER_DATA`), which it will see on every launch, for every release, no problem. If that's a large chunk of data, we have a non-versioned directory `/home/alan/snap/polar-bookshelf/current/.config/PolarData` (`$SNAP_USER_COMMON`). 

It might seem like a problem but it's only an issue if you run both the snap and non-snap build of the application, which in all likelyhood nobody other than you ever will. 

Most users will just install the snap, use it and not actually care where the internal data structures are held. It's a technical detail.

**Comment by burtonator** [comment] 2018-10-25 23:20
I have some code for the default NEW path for creating the PolarData dir ... but it can re-use an existing path if it probes for it and finds it.

I could just add ~//snap/polar-bookshelf/current/.config/PolarData to that scan path

.. this way if you ever install from deb or something you won't lose your data.

**Comment by burtonator** [comment] 2018-10-26 02:20
Can you guys check if 1.0.5 is working?  I just pushed to snap central so might take a while to update

**Comment by popey** [comment] 2018-10-26 11:06
Confirmed 1.0.5 works perfectly!

**Comment by burtonator** [comment] 2018-10-26 14:47
Thanks!  Really appreciate your help here guys!

**Closed by burtonator** 2018-10-26 14:48 UTC
