### ISSUE TITLE
Need to refresh document to make text annotation

### ISSUE THREAD

**Issue by samgalen** [burtonator/polar-bookshelf#430] opened 2018-11-26 21:14 UTC
**Describe the bug**
After making a comment or creating a flashcard, the option to make a text highlight doesn't show up if you don't refresh it.

**To Reproduce**
1. On MacOS 10.11.6, using prepackaged version from DMG, version 1.0.14
2. Create a text highlight comment
3. Either delete a highlight, make a comment, or a flashcard (possibly more, haven't exhaustively tested)
4. highlighting text does not initiate an option to make a text highlight

**Expected behavior**
Highlighting text should always produce the option to create a text highlight

**Screenshots**
Expected behavior/behavior prior to comment modification

![image](https://user-images.githubusercontent.com/10593796/49042416-c144e280-f18d-11e8-89a8-bb29ca16e5bf.png)

Behavior after comment modification

![image](https://user-images.githubusercontent.com/10593796/49042494-ee919080-f18d-11e8-99b5-d5676dae451d.png)

**Desktop (please complete the following information):**
 - OS: MacOS 10.11.16
 - Version 1.0.14

**Comment by roachsinai** [comment] 2018-11-27 02:56
Same issue on Manjaro KDE.

**Comment by burtonator** [comment] 2018-11-27 02:58
only on PDF or HTML too?

**Comment by roachsinai** [comment] 2018-11-27 03:12
Both have happened for me. But seems it could not produced always...

**Comment by kofiav** [comment] 2018-11-28 02:50
I am experiencing the same issue on Ubuntu 16.04 LTS

**Comment by burtonator** [comment] 2018-11-28 22:49
always PDF or HTML?

**Comment by roachsinai** [comment] 2018-11-29 02:53
If pdf is a book which means file size is big(I now reading a 80+ Mb file), this situation often happens.

**Comment by samgalen** [comment] 2018-11-29 03:45
I have only tested it on a 200 kb pdf.

**Comment by distracted-dev** [comment] 2018-12-14 15:59
PDF on Windows. Javascript warning in the console.

`C:\Users\myuser\AppData\Local\Programs\polar-bookshelf\resources\app.asar\node_modules\@sentry\browser\dist\index.js:3680 [warn] [1.1.1] [ControlledPopup.js] Could not find anchor element for id: annotationbar-anchor`

**Comment by burtonator** [comment] 2018-12-14 16:02
Should be fixed in 1.5.0 and later

**Comment by distracted-dev** [comment] 2018-12-14 18:13
`C:\Users\myuser\AppData\Local\Programs\polar-bookshelf\resources\app.asar\node_modules\@sentry\browser\dist\index.js:3680 [warn] [1.5.0] [ControlledPopup.js] Could not find anchor element for id: annotationbar-anchor`

**Comment by burtonator** [comment] 2018-12-14 19:01
ok.. I think I have to properly handle when the element scrolls off screen:

https://github.com/joshwnj/react-visibility-sensor

**Comment by burtonator** [comment] 2018-12-14 19:07
Can you confirm this is true?  

I think it will work properly as long as the popup is hidden when you move between pages.

I think this only happens if the popup is visible and you scroll the PDF dramatically.  It will accidentally remove it from the DOM and then the second time you're not able to use it.

**Comment by distracted-dev** [comment] 2018-12-14 19:46
> I think this only happens if the popup is visible and you scroll the PDF dramatically. It will accidentally remove it from the DOM and then the second time you're not able to use it.

I have tested this and I'm unable to determine a pattern. It's much more robust than it was in previous versions. I'll continue testing.

**Comment by distracted-dev** [comment] 2018-12-14 20:11
I found a consistently reproducible pattern which may be related.

Select a page in the page thumbnails pane. The viewer pane displays that page. Scroll until the next page is visible. Select text from the newly visible page. Select a highlight color from the pop-up. The text selection and the pop-up disappears with a short delay. No highlight appears.

**Comment by burtonator** [comment] 2018-12-14 20:18
OK... well that's a step in the right direction.  I know this is a bug that bothers a lot of people so really want to get it fixed.

**Comment by burtonator** [comment] 2018-12-14 20:18
... ok.. let me test that scenario...

**Comment by burtonator** [comment] 2018-12-14 20:20
... that worked for me but I also made a small change on my end..

**Comment by distracted-dev** [comment] 2018-12-15 08:13
To clarify, my issue happens if X thumbnail is active in the thumbnail pane and I'm selecting text on Y page. I can do this by scrolling just far enough so that I can see text on the following page but before the thumbnail selection automatically switches.

I'll test this again with your next release.

**Comment by stekern** [comment] 2018-12-15 19:08
I'm getting the same problem while reading a 57 page PDF. The problem occurs on both 1.1.1 and 1.5.0. 

Highlighting works for one or maybe two pages, but after this the highlight bar stops appearing when text is selected and the following warning appears in the console

`[ControlledPopup.js] Could not find anchor element for id: annotationbar-anchor`

**Comment by burtonator** [comment] 2018-12-15 23:47
ok.. I sincerely think I fixed it now.. I realized that there is an even WORSE situation that breaks it when you change the zoom.

At that point it's completely dead.  I implemented a hack which forces the widget to constantly be redrawn.

**Comment by burtonator** [comment] 2018-12-15 23:47
Should go out monday...

**Comment by burtonator** [comment] 2018-12-18 00:51
This is out now... can you guys let me know if this works for you in 1.5.1 ?

**Comment by likyng** [comment] 2018-12-18 01:43
I do still have the problem. After I open the comment sidebar, the text highlighters won't pop up anymore. 

Just a suggestion, maybe in addition to fixing the problem normally, would it be possible to have the highlight ability also available from the right-click context menu?

**Comment by burtonator** [comment] 2018-12-18 02:38
And just to confirm you have this with PDFs and 1.5.1?

Well part of the problem is that Electron's right click menu is a bit of a nightmare...

**Comment by kofiav** [comment] 2018-12-18 03:17
Just tried this. For new PDF files that I hadn't already annotated with the previous versions, it seems to be working fine (I'm yet to trigger the bug). However, this isn't the case with PDFs that I previously highlighted. I'm using Ubuntu 16.04.

**Comment by likyng** [comment] 2018-12-18 05:51
Some more infos to reproduce: 
* Using version 1.5.1 (installed from .deb)
1. Open Polar
2. Open PDF File with 2 annotations and no progress
3. Fit to Width
4. Annotate something (works)
5. Open Sidebar
6. Adjust zoom manually to reactivate fit to width dropdown
7. Fit to width
8. Select text --> annotation popup won't popup

**Comment by distracted-dev** [comment] 2018-12-18 12:55
1.5.1 - issue persists with PDF's. Selected text on a page which isn't active doesn't highlight.

As mentioned above, zoom breaks the annotation if the highlight popup is present.

**Comment by burtonator** [comment] 2018-12-18 17:09
maybe you guys are using the UI in a way that I didn't anticipate.

If you could create a video that would be amazing...

what do you mean a page which "isn't active?"

**Comment by burtonator** [comment] 2018-12-20 17:31
OK.. you're right... definitely still isn't working.  I'm going to have to rewrite this component entirely but the good news is that I think it will be actually BETTER this way...

**Comment by burtonator** [comment] 2018-12-20 18:30
@stevemurr can you confirm you're on the latest 1.5.1 when this happens?

I'm going rewrite this for 1.5.2 so that I can control it more directly instead of relying on React internals to do things kind of by side effect.

**Comment by stevemurr** [comment] 2018-12-20 18:38
I was running 1.5.1 from the releases page.  I haven't experienced it while annotating smaller PDF's (1 - 8 pages).  I've only experienced it on a 110 page PDF.

**Comment by jullimullins** [comment] 2018-12-20 22:11
I have this problem too. running w10 on surface pro tablet mode + pen and latest version of pbs. I have only one pdf in the pbs and I run into the annotation problen after comleted only 2 - 3  annotations (just open the pdf and start annotating, nothing else). In tablet mode the keyboard shortcuts aren't too usefull either. It would be great if all shrotcuts could be available through always visible floating tool bar.

**Comment by burtonator** [comment] 2018-12-20 22:56
Tablet mode?  I guess you're using it on surface pro?  You're probably going to have to explain what you need through a video or something as I don't have a surface pro... but it's interesting that there's at least a tablet option for Polar now.

Maybe I have to buy one ;) 

Anyone here from MS that wants to send me a surface pro to port polar to it? :)

**Comment by jullimullins** [comment] 2018-12-22 08:53
Digged into this bit more deaper and I think that the challenges I have faced are related more or less to the fact that I'm using surface pen to do the annotations. If I use the attached keyboard trackpad everything works just fine but when I use the digipen do the annotations the the challeges start. I need to click the pen's side button to do the annotation and this also opens the flowting selection menu in addition to the annotation menu. This doesn't happen when I do the annotion with keyboard's trackpad or with the mouse.
![polarbookshelf](https://user-images.githubusercontent.com/16438266/50372465-5a251d00-05d7-11e9-852b-962bd8884f1c.jpg)

I need to check if I can change the behaviour of the digipens button, so it would work like mouse left button. I think that this would fix this issue.

**Comment by burtonator** [comment] 2018-12-22 18:48
@jullimullins Can we work on Surface changes here:

https://github.com/burtonator/polar-bookshelf/issues/473

**Comment by burtonator** [comment] 2018-12-22 18:48
Can you let me know how this works in 1.6.0 ?  Just released today and mostly rewrote how the annotation bar works behind the scenes.

**Comment by jullimullins** [comment] 2018-12-22 19:11
Look that you nailed this! I really tried to dublicate the earlier problems but haven't succeeded:)

**Comment by burtonator** [comment] 2018-12-22 19:21
Frak yeah! Nice.. I'll leave this open for a while to let others report in...

**Comment by likyng** [comment] 2018-12-25 02:50
Hey, thanks for all the great work. For me on version 1.6.0 (updated through deb package), the error still persists. Here is a video showing it:

1. open PDF
2. Resize pdf
3. Annotate anything (works)
4. Resize document
5. Highlight text --> annotation promt does not pop up.


![ezgif-5-43f1b2136a13](https://user-images.githubusercontent.com/246059/50410286-4c6fd180-083b-11e9-83a8-a391fe1e58ac.gif)

**Comment by burtonator** [comment] 2018-12-25 22:32
Thanks.. this is a different bug but easy to fix.  Thanks!

**Comment by burtonator** [comment] 2018-12-25 23:19
k.. thanks.  should be fixed in the next release. 

The animated gif was super helpful

**Comment by burtonator** [comment] 2019-01-03 01:21
This fixed guys?  Should we close this bug?

**Comment by likyng** [comment] 2019-01-04 08:02
Works for me so far, great job!

**Comment by stekern** [comment] 2019-01-04 12:21
Just updated to v1.7.0, and I am unable to reproduce the problems I mentioned in https://github.com/burtonator/polar-bookshelf/issues/430#issuecomment-447590900 :-) Highlighting seems to be working fine now.

**Comment by burtonator** [comment] 2019-01-04 18:02
Thanks... closing now.

**Closed by burtonator** 2019-01-04 18:02 UTC
