### ISSUE TITLE
Could not show entired captured content after zoomed in.

### ISSUE THREAD

**Issue by roachsinai** [burtonator/polar-bookshelf#431] opened 2018-11-27 03:26 UTC
**Describe the bug**

Polar-bookshelf only show part of captured html after zoom in 200% when scroll down to the end.

**To Reproduce**
1. Capture this webpage: [Written Memories: Understanding, Deriving and Extending the LSTM](https://r2rt.com/written-memories-understanding-deriving-and-extending-the-lstm.html#what-rnns-can-do-choosing-the-time-step)
2. zoom in 200%
3. Scroll down to the end

**Expected behavior**

![screenshot_20181127_111916](https://user-images.githubusercontent.com/9500049/49056347-5c919280-f236-11e8-967f-210471ab6695.png)

The screenshot above shows I could read the bottom of the html when zoomed 100%, I wish same when zoomed 200%.

**current behavior**

![screenshot_20181127_112102](https://user-images.githubusercontent.com/9500049/49056395-8fd42180-f236-11e8-91fe-8e87bace38ea.png)

Can not see the bottom refs of the html when zoomed 200%.

**Desktop (please complete the following information):**
 - OS: Manjaro Kde
 - Browser Chrome
 - Polar Version [1.0.14]

**Additional context**
May the reasom the captured html size is a little big?

**Comment by burtonator** [comment] 2018-11-27 03:31
Agreed.. this is very annoying. I'm going to refactor zoom shortly to implement auto-zoom and also fix some of the small bugs related here.  The problem is that zoom itself is a bit difficult to work with due to some bugs with Electron but might be able to find a work around.

**Comment by burtonator** [comment] 2018-11-28 03:36
will be fixed in the next release.

**Closed** 2018-11-30 17:00 UTC
Labels: blocker
