### ISSUE TITLE
EPUB Support

### ISSUE THREAD

**Issue by infosisio** [burtonator/polar-bookshelf#867] opened 2019-04-23 11:01 UTC
Why not? It would be awesome.

**Comment by burtonator** [comment] 2019-04-23 22:43
Theree are other bugs for epub ... we might implement it via conversion to PDF in more of the short term and hopefully support it directly at some point.

**Comment by arnoo** [comment] 2019-04-24 09:13
There is already an issue for this : https://github.com/burtonator/polar-bookshelf/issues/135

**Comment by burtonator** [comment] 2019-05-21 18:14
Closing as duplicate of #135

**Closed by burtonator** 2019-05-21 18:14 UTC
