### ISSUE TITLE
[Feature Request] Edit & Save documents

### ISSUE THREAD

**Issue by setr** [burtonator/polar-bookshelf#293] opened 2018-10-17 22:53 UTC
Currently can't edit the document at capture-time because of the webview thing, and you can edit but not save the document after capturing (with dev-tools). 

Would be useful for manually cleaning up documents (ie sidebars, ads). Even after automated solutions are implemented (eg readability), it'd be useful as a fallback.

**Comment by burtonator** [comment] 2018-10-18 04:34
> Currently can't edit the document at capture-time because of the webview thing, and you can edit but not save the document after capturing (with dev-tools).

If I gave you dev tools for now could that work?

Then you could delete a whole range.

I think a UI for this would be rough to implement.. IE deleting a whole range of the DOM elements.  Unless there's some simple API that you guys know of for easily chopping out whole sections of the DOM

**Comment by setr** [comment] 2018-10-18 05:03
Dev tools already exists for both the capture UI and the viewing UI, and is
sufficient.

In the capture UI, you can’t actually access the DOM properly, as its
within the webview js, so you can’t do much about it trivially.

In the viewer UI however, you can properly access and edit the DOM with
dev-tools, but as far as I can tell, not save the changes.

Either giving proper DOM access in the capture UI, or the ability to save
changes in the viewer UI would be sufficient for my use case (which boils
down to deleting DOM nodes for the most part).

I imagine the latter is a much less invasive change

**Comment by burtonator** [comment] 2018-10-18 17:41
I'm going to work on a way to kill/nuke element sin the DOM before capture.  Shouldn't be too hard to implement.

**Comment by burtonator** [comment] 2018-10-18 17:45
this is a duplicate of this issue:  Closing this issue to focus on #278 

https://github.com/burtonator/polar-bookshelf/issues/278

**Closed** 2018-10-18 17:45 UTC
Labels: os
