### ISSUE TITLE
Able to edit text in the style editor dialog in annotations pane

### ISSUE THREAD

**Issue by Dawny33** [burtonator/polar-bookshelf#669] opened 2019-03-04 09:11 UTC
NOTE: Polar is supported by community donations.  Bug reports and features are prioritized for people who make a donation: https://opencollective.com/polar-bookshelf

**Describe the bug**
 - I was unable to add a comment in the right annotations pane. This after I already added a comment.\
 - When I try to add text in the comment box, the text is being added to the style editor dialog box

**To Reproduce**
1. Go to 'Create comment' under an annotation
2. Try typing something

**Expected behavior**
The comment text should be reflected in the text box of the comment.

**Screenshots**
![image](https://user-images.githubusercontent.com/4637008/53722147-e2068d80-3e8a-11e9-9c58-b8473cc7cfb0.png)
![image](https://user-images.githubusercontent.com/4637008/53722388-7244d280-3e8b-11e9-98b8-a255b0fb9ba8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Version: 70.0.3538.110 (Official Build) (64-bit)

**Comment by burtonator** [comment] 2019-03-04 17:12
ah.. yes.. this is a bug that's biting a lot of people so we're going to close it out in the next release.  

Sorry for the confusion. 

It's a duplicate of this bug if you want to follow this primary one.

https://github.com/burtonator/polar-bookshelf/issues/662

**Closed by burtonator** 2019-03-04 17:12 UTC
