### ISSUE TITLE
Pagemarks sometimes cannot be deleted 

### ISSUE THREAD

**Issue by warfarincoumadin** [burtonator/polar-bookshelf#542] opened 2019-01-12 14:46 UTC
![image](https://user-images.githubusercontent.com/46626802/51074589-3eb2ac80-1681-11e9-91c3-ec804ab05718.png)

**Comment by warfarincoumadin** [comment] 2019-01-12 14:48
Upon further digging - these are phantom pagemarks which disappear after reopning the pdf reader. Not sure how they get created in the first place.

**Comment by joshchamberlain** [comment] 2019-02-11 23:23
I experienced the same issue. I noticed in the console that deleting the pagemark resulted in an exception due to the undefined property 'batch' on the Pagemark object. Unfortunately, I did not copy the exact error message.

**Comment by joshchamberlain** [comment] 2019-02-11 23:27
The error occurred again:
```
Pagemarks.ts:397 Uncaught TypeError: Cannot read property 'batch' of undefined
    at doDocMetaMutation (Pagemarks.ts:397)
    at DocMetas_1.DocMetas.withBatchedMutations (Pagemarks.ts:465)
    at Function.withBatchedMutations (DocMetas.ts:214)
    at Function.doDocMetaMutation (Pagemarks.ts:463)
    at Function.deletePagemark (Pagemarks.ts:387)
    at PagemarkController.onDeletePagemark (PagemarkController.ts:158)
    at PagemarkController.onMessageReceived (PagemarkController.ts:52)
    at window.addEventListener.event (PagemarkController.ts:35)
```

Which is the following code:
```typescript
    /**
     *
     * @param id When id is specified we delete just a specific pagemark,
     * otherwise we delete all of them.
     */
    public static deletePagemark(docMeta: DocMeta, pageNum: number, id?: string) {

        this.doDocMetaMutation(docMeta, pageNum, () => {

            const pageMeta = DocMetas.getPageMeta(docMeta, pageNum);

            let pageMetaMutator: VOID_FUNCTION | undefined;

            if (id) {

                const primaryPagemark = pageMeta.pagemarks[id];

                if (primaryPagemark.batch) {
```

**Comment by burtonator** [comment] 2019-02-14 20:52
Hey.. could you test something for me?  Could you do this again but make sure the page on which you're deleting the pagemark is 100% of the entire viewport / window?

I think that's the bug.  If so I'm going to try another workaround...

**Comment by joshchamberlain** [comment] 2019-02-22 00:17
I still haven't managed to reproduce the bug. Sorry.

**Comment by burtonator** [comment] 2019-02-22 15:58
I actually think this is fixed now... 

Kevin

**Closed by burtonator** 2019-02-22 15:58 UTC
